labels = {
    "jp": {
        "title": "LangPont 翻訳アプリ",
        "translate_button": "翻訳する",
        "reset_button": "リセット",
        "input_label": "翻訳したい文章",
        "placeholder_input": "ここに翻訳したい文章を入力",
        "placeholder_context": "背景情報を入力してください",
        "default_context": "私はフランス人とビジネスをしていて、相手は私のお客様です。",
        "additional_question": "追加の質問を入力:",
        "placeholder_followup": "さらに質問したい内容を入力してください",
        "button_submit_question": "質問を送信する",
        "answer_title": "ChatGPTの回答:",
        "history_title": "質問と回答の履歴:",
        "toast_copied": "コピーしました！",
        "toggle_details_open": "▼ 詳細入力を表示",
        "toggle_details_close": "▲ 詳細入力を閉じる",
        "section_chatgpt": "ChatGPTによる翻訳",
        "section_better": "より良い翻訳提案（ChatGPT）",
        "section_gemini": "Geminiによる翻訳",
        "gemini_nuance_title": "Geminiによる3文のニュアンス解析:",
        "gemini_loading": "🧠 ニュアンス分析を取得中...",
        "gemini_failed": "⚠️ Gemini分析に失敗しました",
        "label_french": "フランス語",
        "label_japanese": "日本語訳",
        "label_partner_message": "直前の会話のやり取り（任意）",
        "label_context_info": "背景情報",
        "button_gemini": "🧠 Geminiニュアンスを取得する",
        "logout": "ログアウト",
        "lang_switch": "言語切替",
        "page_title": "LangPont 翻訳アプリ",
        "loading_message": "翻訳中です… 少々お待ちください。",
        "label_ja": "日本語",
        "label_fr": "フランス語",
        "label_en": "英語",
        # 🆕 インタラクティブ機能用ラベル
        "interactive_title": "追加の質問・リクエスト",
        "interactive_placeholder": "例：「もう少し親近感のある表現にしてください」「1番目の翻訳のXXXはどういう意味ですか？」",
        "interactive_button": "質問する",
        "chat_history_title": "質問・回答履歴",
        "chat_clear_button": "履歴をクリア",
        "quick_friendly": "もっと親しみやすく",
        "quick_formal": "もっとフォーマルに",
        "quick_combine": "翻訳を組み合わせ",
        "quick_natural": "どれが自然？",
        "quick_business": "ビジネス向け",
        "chat_cleared": "履歴をクリアしました",
        "question_generated": "質問への回答を生成しました",
        "error_occurred": "エラーが発生しました",
        "processing": "処理中",
        "enter_question": "質問を入力してください"
    },
    "en": {
        "title": "LangPont Translator",
        "translate_button": "Translate",
        "reset_button": "Reset",
        "input_label": "Enter text to translate",
        "placeholder_input": "Enter text to translate",
        "placeholder_context": "Enter background context if any",
        "default_context": "I am working with a French client. They are my customer.",
        "additional_question": "Enter a follow-up question:",
        "placeholder_followup": "Enter your follow-up question",
        "button_submit_question": "Submit Question",
        "answer_title": "ChatGPT's Answer:",
        "history_title": "Q&A History:",
        "toast_copied": "Copied!",
        "toggle_details_open": "▼ Show details",
        "toggle_details_close": "▲ Hide details",
        "section_chatgpt": "Translation by ChatGPT",
        "section_better": "Improved translation (ChatGPT)",
        "section_gemini": "Translation by Gemini",
        "gemini_nuance_title": "Gemini's Nuance Analysis (3 Sentences):",
        "gemini_loading": "🧠 Analyzing nuance with Gemini...",
        "gemini_failed": "⚠️ Failed to analyze with Gemini.",
        "label_french": "French",
        "label_japanese": "Japanese",
        "label_partner_message": "Prior conversation (optional)",
        "label_context_info": "Background information",
        "button_gemini": "🧠 Get Gemini Nuance",
        "logout": "Logout",
        "lang_switch": "Language",
        "page_title": "LangPont Translation App",
        "loading_message": "Translating… Please wait.",
        "label_ja": "Japanese",
        "label_fr": "French",
        "label_en": "English",
        # 🆕 Interactive feature labels
        "interactive_title": "Additional Questions & Requests",
        "interactive_placeholder": "e.g., \"Make it more friendly\" \"What does XXX in the 1st translation mean?\"",
        "interactive_button": "Ask",
        "chat_history_title": "Question & Answer History",
        "chat_clear_button": "Clear History",
        "quick_friendly": "More friendly",
        "quick_formal": "More formal",
        "quick_combine": "Combine translations",
        "quick_natural": "Which is natural?",
        "quick_business": "Business-oriented",
        "chat_cleared": "History cleared",
        "question_generated": "Response generated successfully",
        "error_occurred": "An error occurred",
        "processing": "Processing",
        "enter_question": "Please enter a question"
    },
    "fr": {
        "title": "LangPont Traducteur",
        "translate_button": "Traduire",
        "reset_button": "Réinitialiser",
        "input_label": "Entrez le texte à traduire",
        "placeholder_input": "Veuillez entrer le texte que vous souhaitez traduire ici.",
        "placeholder_context": "Entrez les informations contextuelles si nécessaire",
        "default_context": "Je travaille avec un client français. C'est mon client.",
        "additional_question": "Entrez une question complémentaire :",
        "placeholder_followup": "Saisissez votre question complémentaire",
        "button_submit_question": "Envoyer la question",
        "answer_title": "Réponse de ChatGPT :",
        "history_title": "Historique des questions-réponses :",
        "toast_copied": "Copié !",
        "toggle_details_open": "▼ Afficher les détails",
        "toggle_details_close": "▲ Masquer les détails",
        "section_chatgpt": "Traduction par ChatGPT",
        "section_better": "Traduction améliorée (ChatGPT)",
        "section_gemini": "Traduction par Gemini",
        "gemini_nuance_title": "Analyse de nuance par Gemini (3 phrases) :",
        "gemini_loading": "🧠 Analyse de la nuance avec Gemini...",
        "gemini_failed": "⚠️ L'analyse avec Gemini a échoué.",
        "label_french": "Français",
        "label_japanese": "Japonais",
        "label_partner_message": "Veuillez saisir l'échange de conversation précédent.",
        "label_context_info": "Contexte",
        "button_gemini": "🧠 Obtenir l'analyse Gemini",
        "logout": "Déconnexion",
        "lang_switch": "Langue",
        "page_title": "LangPont Traduction App",
        "loading_message": "Traduction en cours… Un instant, s'il vous plaît.",
        "label_ja": "le japonais",
        "label_fr": "le français",
        "label_en": "l'anglais",
        # 🆕 Étiquettes des fonctionnalités interactives
        "interactive_title": "Questions et Demandes Supplémentaires",
        "interactive_placeholder": "ex: \"Rendez-le plus amical\" \"Que signifie XXX dans la 1ère traduction?\"",
        "interactive_button": "Demander",
        "chat_history_title": "Historique Questions & Réponses",
        "chat_clear_button": "Effacer l'historique",
        "quick_friendly": "Plus amical",
        "quick_formal": "Plus formel",
        "quick_combine": "Combiner traductions",
        "quick_natural": "Lequel est naturel?",
        "quick_business": "Orienté business",
        "chat_cleared": "Historique effacé",
        "question_generated": "Réponse générée avec succès",
        "error_occurred": "Une erreur s'est produite",
        "processing": "En cours de traitement",
        "enter_question": "Veuillez saisir une question"
    }
}